// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventsequencer.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "eventsequencer.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pb {

namespace {

const ::google::protobuf::Descriptor* Strip_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Strip_reflection_ = NULL;
const ::google::protobuf::Descriptor* Document_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Document_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_eventsequencer_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_eventsequencer_2eproto() {
  protobuf_AddDesc_eventsequencer_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "eventsequencer.proto");
  GOOGLE_CHECK(file != NULL);
  Strip_descriptor_ = file->message_type(0);
  static const int Strip_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strip, channel_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strip, startframe_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strip, length_),
  };
  Strip_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Strip_descriptor_,
      Strip::default_instance_,
      Strip_offsets_,
      -1,
      -1,
      -1,
      sizeof(Strip),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strip, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strip, _is_default_instance_));
  Document_descriptor_ = file->message_type(1);
  static const int Document_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Document, strips_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Document, framespersecond_),
  };
  Document_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Document_descriptor_,
      Document::default_instance_,
      Document_offsets_,
      -1,
      -1,
      -1,
      sizeof(Document),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Document, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Document, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_eventsequencer_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Strip_descriptor_, &Strip::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Document_descriptor_, &Document::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_eventsequencer_2eproto() {
  delete Strip::default_instance_;
  delete Strip_reflection_;
  delete Document::default_instance_;
  delete Document_reflection_;
}

void protobuf_AddDesc_eventsequencer_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_eventsequencer_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024eventsequencer.proto\022\002pb\"<\n\005Strip\022\017\n\007c"
    "hannel\030\001 \001(\005\022\022\n\nstartFrame\030\002 \001(\005\022\016\n\006leng"
    "th\030\003 \001(\005\">\n\010Document\022\031\n\006strips\030\001 \003(\0132\t.p"
    "b.Strip\022\027\n\017framesPerSecond\030\002 \001(\005b\006proto3", 160);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "eventsequencer.proto", &protobuf_RegisterTypes);
  Strip::default_instance_ = new Strip();
  Document::default_instance_ = new Document();
  Strip::default_instance_->InitAsDefaultInstance();
  Document::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_eventsequencer_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_eventsequencer_2eproto {
  StaticDescriptorInitializer_eventsequencer_2eproto() {
    protobuf_AddDesc_eventsequencer_2eproto();
  }
} static_descriptor_initializer_eventsequencer_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Strip::kChannelFieldNumber;
const int Strip::kStartFrameFieldNumber;
const int Strip::kLengthFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Strip::Strip()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.Strip)
}

void Strip::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Strip::Strip(const Strip& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb.Strip)
}

void Strip::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  channel_ = 0;
  startframe_ = 0;
  length_ = 0;
}

Strip::~Strip() {
  // @@protoc_insertion_point(destructor:pb.Strip)
  SharedDtor();
}

void Strip::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Strip::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Strip::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Strip_descriptor_;
}

const Strip& Strip::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_eventsequencer_2eproto();
  return *default_instance_;
}

Strip* Strip::default_instance_ = NULL;

Strip* Strip::New(::google::protobuf::Arena* arena) const {
  Strip* n = new Strip;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Strip::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.Strip)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(Strip, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Strip*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(channel_, length_);

#undef ZR_HELPER_
#undef ZR_

}

bool Strip::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.Strip)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 channel = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &channel_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_startFrame;
        break;
      }

      // optional int32 startFrame = 2;
      case 2: {
        if (tag == 16) {
         parse_startFrame:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &startframe_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_length;
        break;
      }

      // optional int32 length = 3;
      case 3: {
        if (tag == 24) {
         parse_length:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &length_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.Strip)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.Strip)
  return false;
#undef DO_
}

void Strip::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.Strip)
  // optional int32 channel = 1;
  if (this->channel() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->channel(), output);
  }

  // optional int32 startFrame = 2;
  if (this->startframe() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->startframe(), output);
  }

  // optional int32 length = 3;
  if (this->length() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->length(), output);
  }

  // @@protoc_insertion_point(serialize_end:pb.Strip)
}

::google::protobuf::uint8* Strip::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.Strip)
  // optional int32 channel = 1;
  if (this->channel() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->channel(), target);
  }

  // optional int32 startFrame = 2;
  if (this->startframe() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->startframe(), target);
  }

  // optional int32 length = 3;
  if (this->length() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->length(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb.Strip)
  return target;
}

int Strip::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pb.Strip)
  int total_size = 0;

  // optional int32 channel = 1;
  if (this->channel() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->channel());
  }

  // optional int32 startFrame = 2;
  if (this->startframe() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->startframe());
  }

  // optional int32 length = 3;
  if (this->length() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->length());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Strip::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.Strip)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Strip* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Strip>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.Strip)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.Strip)
    MergeFrom(*source);
  }
}

void Strip::MergeFrom(const Strip& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.Strip)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.channel() != 0) {
    set_channel(from.channel());
  }
  if (from.startframe() != 0) {
    set_startframe(from.startframe());
  }
  if (from.length() != 0) {
    set_length(from.length());
  }
}

void Strip::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.Strip)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Strip::CopyFrom(const Strip& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.Strip)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Strip::IsInitialized() const {

  return true;
}

void Strip::Swap(Strip* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Strip::InternalSwap(Strip* other) {
  std::swap(channel_, other->channel_);
  std::swap(startframe_, other->startframe_);
  std::swap(length_, other->length_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Strip::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Strip_descriptor_;
  metadata.reflection = Strip_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Strip

// optional int32 channel = 1;
void Strip::clear_channel() {
  channel_ = 0;
}
 ::google::protobuf::int32 Strip::channel() const {
  // @@protoc_insertion_point(field_get:pb.Strip.channel)
  return channel_;
}
 void Strip::set_channel(::google::protobuf::int32 value) {
  
  channel_ = value;
  // @@protoc_insertion_point(field_set:pb.Strip.channel)
}

// optional int32 startFrame = 2;
void Strip::clear_startframe() {
  startframe_ = 0;
}
 ::google::protobuf::int32 Strip::startframe() const {
  // @@protoc_insertion_point(field_get:pb.Strip.startFrame)
  return startframe_;
}
 void Strip::set_startframe(::google::protobuf::int32 value) {
  
  startframe_ = value;
  // @@protoc_insertion_point(field_set:pb.Strip.startFrame)
}

// optional int32 length = 3;
void Strip::clear_length() {
  length_ = 0;
}
 ::google::protobuf::int32 Strip::length() const {
  // @@protoc_insertion_point(field_get:pb.Strip.length)
  return length_;
}
 void Strip::set_length(::google::protobuf::int32 value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:pb.Strip.length)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Document::kStripsFieldNumber;
const int Document::kFramesPerSecondFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Document::Document()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.Document)
}

void Document::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Document::Document(const Document& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb.Document)
}

void Document::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  framespersecond_ = 0;
}

Document::~Document() {
  // @@protoc_insertion_point(destructor:pb.Document)
  SharedDtor();
}

void Document::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Document::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Document::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Document_descriptor_;
}

const Document& Document::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_eventsequencer_2eproto();
  return *default_instance_;
}

Document* Document::default_instance_ = NULL;

Document* Document::New(::google::protobuf::Arena* arena) const {
  Document* n = new Document;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Document::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.Document)
  framespersecond_ = 0;
  strips_.Clear();
}

bool Document::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.Document)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .pb.Strip strips = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_strips:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_strips()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_strips;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(16)) goto parse_framesPerSecond;
        break;
      }

      // optional int32 framesPerSecond = 2;
      case 2: {
        if (tag == 16) {
         parse_framesPerSecond:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &framespersecond_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.Document)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.Document)
  return false;
#undef DO_
}

void Document::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.Document)
  // repeated .pb.Strip strips = 1;
  for (unsigned int i = 0, n = this->strips_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->strips(i), output);
  }

  // optional int32 framesPerSecond = 2;
  if (this->framespersecond() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->framespersecond(), output);
  }

  // @@protoc_insertion_point(serialize_end:pb.Document)
}

::google::protobuf::uint8* Document::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.Document)
  // repeated .pb.Strip strips = 1;
  for (unsigned int i = 0, n = this->strips_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->strips(i), false, target);
  }

  // optional int32 framesPerSecond = 2;
  if (this->framespersecond() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->framespersecond(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb.Document)
  return target;
}

int Document::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pb.Document)
  int total_size = 0;

  // optional int32 framesPerSecond = 2;
  if (this->framespersecond() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->framespersecond());
  }

  // repeated .pb.Strip strips = 1;
  total_size += 1 * this->strips_size();
  for (int i = 0; i < this->strips_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->strips(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Document::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.Document)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Document* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Document>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.Document)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.Document)
    MergeFrom(*source);
  }
}

void Document::MergeFrom(const Document& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.Document)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  strips_.MergeFrom(from.strips_);
  if (from.framespersecond() != 0) {
    set_framespersecond(from.framespersecond());
  }
}

void Document::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.Document)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Document::CopyFrom(const Document& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.Document)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Document::IsInitialized() const {

  return true;
}

void Document::Swap(Document* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Document::InternalSwap(Document* other) {
  strips_.UnsafeArenaSwap(&other->strips_);
  std::swap(framespersecond_, other->framespersecond_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Document::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Document_descriptor_;
  metadata.reflection = Document_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Document

// repeated .pb.Strip strips = 1;
int Document::strips_size() const {
  return strips_.size();
}
void Document::clear_strips() {
  strips_.Clear();
}
const ::pb::Strip& Document::strips(int index) const {
  // @@protoc_insertion_point(field_get:pb.Document.strips)
  return strips_.Get(index);
}
::pb::Strip* Document::mutable_strips(int index) {
  // @@protoc_insertion_point(field_mutable:pb.Document.strips)
  return strips_.Mutable(index);
}
::pb::Strip* Document::add_strips() {
  // @@protoc_insertion_point(field_add:pb.Document.strips)
  return strips_.Add();
}
::google::protobuf::RepeatedPtrField< ::pb::Strip >*
Document::mutable_strips() {
  // @@protoc_insertion_point(field_mutable_list:pb.Document.strips)
  return &strips_;
}
const ::google::protobuf::RepeatedPtrField< ::pb::Strip >&
Document::strips() const {
  // @@protoc_insertion_point(field_list:pb.Document.strips)
  return strips_;
}

// optional int32 framesPerSecond = 2;
void Document::clear_framespersecond() {
  framespersecond_ = 0;
}
 ::google::protobuf::int32 Document::framespersecond() const {
  // @@protoc_insertion_point(field_get:pb.Document.framesPerSecond)
  return framespersecond_;
}
 void Document::set_framespersecond(::google::protobuf::int32 value) {
  
  framespersecond_ = value;
  // @@protoc_insertion_point(field_set:pb.Document.framesPerSecond)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)
