// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventsequencer.proto

#ifndef PROTOBUF_eventsequencer_2eproto__INCLUDED
#define PROTOBUF_eventsequencer_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_eventsequencer_2eproto();
void protobuf_AssignDesc_eventsequencer_2eproto();
void protobuf_ShutdownFile_eventsequencer_2eproto();

class Document;
class Strip;
class Strip_BadJs;

// ===================================================================

class Strip_BadJs : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb.Strip.BadJs) */ {
 public:
  Strip_BadJs();
  virtual ~Strip_BadJs();

  Strip_BadJs(const Strip_BadJs& from);

  inline Strip_BadJs& operator=(const Strip_BadJs& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Strip_BadJs& default_instance();

  void Swap(Strip_BadJs* other);

  // implements Message ----------------------------------------------

  inline Strip_BadJs* New() const { return New(NULL); }

  Strip_BadJs* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Strip_BadJs& from);
  void MergeFrom(const Strip_BadJs& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Strip_BadJs* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string script = 1;
  void clear_script();
  static const int kScriptFieldNumber = 1;
  const ::std::string& script() const;
  void set_script(const ::std::string& value);
  void set_script(const char* value);
  void set_script(const char* value, size_t size);
  ::std::string* mutable_script();
  ::std::string* release_script();
  void set_allocated_script(::std::string* script);

  // @@protoc_insertion_point(class_scope:pb.Strip.BadJs)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr script_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_eventsequencer_2eproto();
  friend void protobuf_AssignDesc_eventsequencer_2eproto();
  friend void protobuf_ShutdownFile_eventsequencer_2eproto();

  void InitAsDefaultInstance();
  static Strip_BadJs* default_instance_;
};
// -------------------------------------------------------------------

class Strip : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb.Strip) */ {
 public:
  Strip();
  virtual ~Strip();

  Strip(const Strip& from);

  inline Strip& operator=(const Strip& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Strip& default_instance();

  void Swap(Strip* other);

  // implements Message ----------------------------------------------

  inline Strip* New() const { return New(NULL); }

  Strip* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Strip& from);
  void MergeFrom(const Strip& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Strip* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Strip_BadJs BadJs;

  // accessors -------------------------------------------------------

  // optional int32 channel = 1;
  void clear_channel();
  static const int kChannelFieldNumber = 1;
  ::google::protobuf::int32 channel() const;
  void set_channel(::google::protobuf::int32 value);

  // optional int32 startFrame = 2;
  void clear_startframe();
  static const int kStartFrameFieldNumber = 2;
  ::google::protobuf::int32 startframe() const;
  void set_startframe(::google::protobuf::int32 value);

  // optional int32 length = 3;
  void clear_length();
  static const int kLengthFieldNumber = 3;
  ::google::protobuf::int32 length() const;
  void set_length(::google::protobuf::int32 value);

  // optional .pb.Strip.BadJs badJs = 10;
  bool has_badjs() const;
  void clear_badjs();
  static const int kBadJsFieldNumber = 10;
  const ::pb::Strip_BadJs& badjs() const;
  ::pb::Strip_BadJs* mutable_badjs();
  ::pb::Strip_BadJs* release_badjs();
  void set_allocated_badjs(::pb::Strip_BadJs* badjs);

  // @@protoc_insertion_point(class_scope:pb.Strip)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 channel_;
  ::google::protobuf::int32 startframe_;
  ::pb::Strip_BadJs* badjs_;
  ::google::protobuf::int32 length_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_eventsequencer_2eproto();
  friend void protobuf_AssignDesc_eventsequencer_2eproto();
  friend void protobuf_ShutdownFile_eventsequencer_2eproto();

  void InitAsDefaultInstance();
  static Strip* default_instance_;
};
// -------------------------------------------------------------------

class Document : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb.Document) */ {
 public:
  Document();
  virtual ~Document();

  Document(const Document& from);

  inline Document& operator=(const Document& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Document& default_instance();

  void Swap(Document* other);

  // implements Message ----------------------------------------------

  inline Document* New() const { return New(NULL); }

  Document* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Document& from);
  void MergeFrom(const Document& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Document* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pb.Strip strips = 1;
  int strips_size() const;
  void clear_strips();
  static const int kStripsFieldNumber = 1;
  const ::pb::Strip& strips(int index) const;
  ::pb::Strip* mutable_strips(int index);
  ::pb::Strip* add_strips();
  ::google::protobuf::RepeatedPtrField< ::pb::Strip >*
      mutable_strips();
  const ::google::protobuf::RepeatedPtrField< ::pb::Strip >&
      strips() const;

  // optional int32 framesPerSecond = 2;
  void clear_framespersecond();
  static const int kFramesPerSecondFieldNumber = 2;
  ::google::protobuf::int32 framespersecond() const;
  void set_framespersecond(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pb.Document)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::pb::Strip > strips_;
  ::google::protobuf::int32 framespersecond_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_eventsequencer_2eproto();
  friend void protobuf_AssignDesc_eventsequencer_2eproto();
  friend void protobuf_ShutdownFile_eventsequencer_2eproto();

  void InitAsDefaultInstance();
  static Document* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Strip_BadJs

// optional string script = 1;
inline void Strip_BadJs::clear_script() {
  script_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Strip_BadJs::script() const {
  // @@protoc_insertion_point(field_get:pb.Strip.BadJs.script)
  return script_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Strip_BadJs::set_script(const ::std::string& value) {
  
  script_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.Strip.BadJs.script)
}
inline void Strip_BadJs::set_script(const char* value) {
  
  script_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.Strip.BadJs.script)
}
inline void Strip_BadJs::set_script(const char* value, size_t size) {
  
  script_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.Strip.BadJs.script)
}
inline ::std::string* Strip_BadJs::mutable_script() {
  
  // @@protoc_insertion_point(field_mutable:pb.Strip.BadJs.script)
  return script_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Strip_BadJs::release_script() {
  // @@protoc_insertion_point(field_release:pb.Strip.BadJs.script)
  
  return script_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Strip_BadJs::set_allocated_script(::std::string* script) {
  if (script != NULL) {
    
  } else {
    
  }
  script_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), script);
  // @@protoc_insertion_point(field_set_allocated:pb.Strip.BadJs.script)
}

// -------------------------------------------------------------------

// Strip

// optional int32 channel = 1;
inline void Strip::clear_channel() {
  channel_ = 0;
}
inline ::google::protobuf::int32 Strip::channel() const {
  // @@protoc_insertion_point(field_get:pb.Strip.channel)
  return channel_;
}
inline void Strip::set_channel(::google::protobuf::int32 value) {
  
  channel_ = value;
  // @@protoc_insertion_point(field_set:pb.Strip.channel)
}

// optional int32 startFrame = 2;
inline void Strip::clear_startframe() {
  startframe_ = 0;
}
inline ::google::protobuf::int32 Strip::startframe() const {
  // @@protoc_insertion_point(field_get:pb.Strip.startFrame)
  return startframe_;
}
inline void Strip::set_startframe(::google::protobuf::int32 value) {
  
  startframe_ = value;
  // @@protoc_insertion_point(field_set:pb.Strip.startFrame)
}

// optional int32 length = 3;
inline void Strip::clear_length() {
  length_ = 0;
}
inline ::google::protobuf::int32 Strip::length() const {
  // @@protoc_insertion_point(field_get:pb.Strip.length)
  return length_;
}
inline void Strip::set_length(::google::protobuf::int32 value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:pb.Strip.length)
}

// optional .pb.Strip.BadJs badJs = 10;
inline bool Strip::has_badjs() const {
  return !_is_default_instance_ && badjs_ != NULL;
}
inline void Strip::clear_badjs() {
  if (GetArenaNoVirtual() == NULL && badjs_ != NULL) delete badjs_;
  badjs_ = NULL;
}
inline const ::pb::Strip_BadJs& Strip::badjs() const {
  // @@protoc_insertion_point(field_get:pb.Strip.badJs)
  return badjs_ != NULL ? *badjs_ : *default_instance_->badjs_;
}
inline ::pb::Strip_BadJs* Strip::mutable_badjs() {
  
  if (badjs_ == NULL) {
    badjs_ = new ::pb::Strip_BadJs;
  }
  // @@protoc_insertion_point(field_mutable:pb.Strip.badJs)
  return badjs_;
}
inline ::pb::Strip_BadJs* Strip::release_badjs() {
  // @@protoc_insertion_point(field_release:pb.Strip.badJs)
  
  ::pb::Strip_BadJs* temp = badjs_;
  badjs_ = NULL;
  return temp;
}
inline void Strip::set_allocated_badjs(::pb::Strip_BadJs* badjs) {
  delete badjs_;
  badjs_ = badjs;
  if (badjs) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:pb.Strip.badJs)
}

// -------------------------------------------------------------------

// Document

// repeated .pb.Strip strips = 1;
inline int Document::strips_size() const {
  return strips_.size();
}
inline void Document::clear_strips() {
  strips_.Clear();
}
inline const ::pb::Strip& Document::strips(int index) const {
  // @@protoc_insertion_point(field_get:pb.Document.strips)
  return strips_.Get(index);
}
inline ::pb::Strip* Document::mutable_strips(int index) {
  // @@protoc_insertion_point(field_mutable:pb.Document.strips)
  return strips_.Mutable(index);
}
inline ::pb::Strip* Document::add_strips() {
  // @@protoc_insertion_point(field_add:pb.Document.strips)
  return strips_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::pb::Strip >*
Document::mutable_strips() {
  // @@protoc_insertion_point(field_mutable_list:pb.Document.strips)
  return &strips_;
}
inline const ::google::protobuf::RepeatedPtrField< ::pb::Strip >&
Document::strips() const {
  // @@protoc_insertion_point(field_list:pb.Document.strips)
  return strips_;
}

// optional int32 framesPerSecond = 2;
inline void Document::clear_framespersecond() {
  framespersecond_ = 0;
}
inline ::google::protobuf::int32 Document::framespersecond() const {
  // @@protoc_insertion_point(field_get:pb.Document.framesPerSecond)
  return framespersecond_;
}
inline void Document::set_framespersecond(::google::protobuf::int32 value) {
  
  framespersecond_ = value;
  // @@protoc_insertion_point(field_set:pb.Document.framesPerSecond)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_eventsequencer_2eproto__INCLUDED
