// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventsequencer.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "eventsequencer.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pb {

namespace {

const ::google::protobuf::Descriptor* Strip_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Strip_reflection_ = NULL;
const ::google::protobuf::Descriptor* Strip_BadJs_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Strip_BadJs_reflection_ = NULL;
const ::google::protobuf::Descriptor* ChannelData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ChannelData_reflection_ = NULL;
struct ChannelDataOneofInstance {
  const ::pb::ChannelData_BadClock* badclock_;
  const ::pb::ChannelData_BadJs* badjs_;
  const ::pb::ChannelData_Text* text_;
  const ::pb::ChannelData_Audio* audio_;
}* ChannelData_default_oneof_instance_ = NULL;
const ::google::protobuf::Descriptor* ChannelData_BadClock_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ChannelData_BadClock_reflection_ = NULL;
const ::google::protobuf::Descriptor* ChannelData_BadJs_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ChannelData_BadJs_reflection_ = NULL;
const ::google::protobuf::Descriptor* ChannelData_Text_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ChannelData_Text_reflection_ = NULL;
const ::google::protobuf::Descriptor* ChannelData_Audio_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ChannelData_Audio_reflection_ = NULL;
const ::google::protobuf::Descriptor* Document_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Document_reflection_ = NULL;
const ::google::protobuf::Descriptor* Document_ChannelsEntry_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_eventsequencer_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_eventsequencer_2eproto() {
  protobuf_AddDesc_eventsequencer_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "eventsequencer.proto");
  GOOGLE_CHECK(file != NULL);
  Strip_descriptor_ = file->message_type(0);
  static const int Strip_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strip, channel_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strip, startframe_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strip, length_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strip, badjs_),
  };
  Strip_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Strip_descriptor_,
      Strip::default_instance_,
      Strip_offsets_,
      -1,
      -1,
      -1,
      sizeof(Strip),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strip, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strip, _is_default_instance_));
  Strip_BadJs_descriptor_ = Strip_descriptor_->nested_type(0);
  static const int Strip_BadJs_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strip_BadJs, script_),
  };
  Strip_BadJs_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Strip_BadJs_descriptor_,
      Strip_BadJs::default_instance_,
      Strip_BadJs_offsets_,
      -1,
      -1,
      -1,
      sizeof(Strip_BadJs),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strip_BadJs, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strip_BadJs, _is_default_instance_));
  ChannelData_descriptor_ = file->message_type(1);
  static const int ChannelData_offsets_[5] = {
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(ChannelData_default_oneof_instance_, badclock_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(ChannelData_default_oneof_instance_, badjs_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(ChannelData_default_oneof_instance_, text_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(ChannelData_default_oneof_instance_, audio_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChannelData, channel_),
  };
  ChannelData_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ChannelData_descriptor_,
      ChannelData::default_instance_,
      ChannelData_offsets_,
      -1,
      -1,
      -1,
      ChannelData_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChannelData, _oneof_case_[0]),
      sizeof(ChannelData),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChannelData, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChannelData, _is_default_instance_));
  ChannelData_BadClock_descriptor_ = ChannelData_descriptor_->nested_type(0);
  static const int ChannelData_BadClock_offsets_[1] = {
  };
  ChannelData_BadClock_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ChannelData_BadClock_descriptor_,
      ChannelData_BadClock::default_instance_,
      ChannelData_BadClock_offsets_,
      -1,
      -1,
      -1,
      sizeof(ChannelData_BadClock),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChannelData_BadClock, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChannelData_BadClock, _is_default_instance_));
  ChannelData_BadJs_descriptor_ = ChannelData_descriptor_->nested_type(1);
  static const int ChannelData_BadJs_offsets_[1] = {
  };
  ChannelData_BadJs_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ChannelData_BadJs_descriptor_,
      ChannelData_BadJs::default_instance_,
      ChannelData_BadJs_offsets_,
      -1,
      -1,
      -1,
      sizeof(ChannelData_BadJs),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChannelData_BadJs, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChannelData_BadJs, _is_default_instance_));
  ChannelData_Text_descriptor_ = ChannelData_descriptor_->nested_type(2);
  static const int ChannelData_Text_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChannelData_Text, fontsize_),
  };
  ChannelData_Text_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ChannelData_Text_descriptor_,
      ChannelData_Text::default_instance_,
      ChannelData_Text_offsets_,
      -1,
      -1,
      -1,
      sizeof(ChannelData_Text),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChannelData_Text, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChannelData_Text, _is_default_instance_));
  ChannelData_Audio_descriptor_ = ChannelData_descriptor_->nested_type(3);
  static const int ChannelData_Audio_offsets_[1] = {
  };
  ChannelData_Audio_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ChannelData_Audio_descriptor_,
      ChannelData_Audio::default_instance_,
      ChannelData_Audio_offsets_,
      -1,
      -1,
      -1,
      sizeof(ChannelData_Audio),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChannelData_Audio, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChannelData_Audio, _is_default_instance_));
  Document_descriptor_ = file->message_type(2);
  static const int Document_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Document, strips_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Document, framespersecond_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Document, startframe_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Document, endframe_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Document, channels_),
  };
  Document_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Document_descriptor_,
      Document::default_instance_,
      Document_offsets_,
      -1,
      -1,
      -1,
      sizeof(Document),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Document, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Document, _is_default_instance_));
  Document_ChannelsEntry_descriptor_ = Document_descriptor_->nested_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_eventsequencer_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Strip_descriptor_, &Strip::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Strip_BadJs_descriptor_, &Strip_BadJs::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ChannelData_descriptor_, &ChannelData::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ChannelData_BadClock_descriptor_, &ChannelData_BadClock::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ChannelData_BadJs_descriptor_, &ChannelData_BadJs::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ChannelData_Text_descriptor_, &ChannelData_Text::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ChannelData_Audio_descriptor_, &ChannelData_Audio::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Document_descriptor_, &Document::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
        Document_ChannelsEntry_descriptor_,
        ::google::protobuf::internal::MapEntry<
            ::google::protobuf::int32,
            ::pb::ChannelData,
            ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
            ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
            0>::CreateDefaultInstance(
                Document_ChannelsEntry_descriptor_));
}

}  // namespace

void protobuf_ShutdownFile_eventsequencer_2eproto() {
  delete Strip::default_instance_;
  delete Strip_reflection_;
  delete Strip_BadJs::default_instance_;
  delete Strip_BadJs_reflection_;
  delete ChannelData::default_instance_;
  delete ChannelData_default_oneof_instance_;
  delete ChannelData_reflection_;
  delete ChannelData_BadClock::default_instance_;
  delete ChannelData_BadClock_reflection_;
  delete ChannelData_BadJs::default_instance_;
  delete ChannelData_BadJs_reflection_;
  delete ChannelData_Text::default_instance_;
  delete ChannelData_Text_reflection_;
  delete ChannelData_Audio::default_instance_;
  delete ChannelData_Audio_reflection_;
  delete Document::default_instance_;
  delete Document_reflection_;
}

void protobuf_AddDesc_eventsequencer_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_eventsequencer_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024eventsequencer.proto\022\002pb\"u\n\005Strip\022\017\n\007c"
    "hannel\030\001 \001(\005\022\022\n\nstartFrame\030\002 \001(\005\022\016\n\006leng"
    "th\030\003 \001(\005\022\036\n\005badJs\030\n \001(\0132\017.pb.Strip.BadJs"
    "\032\027\n\005BadJs\022\016\n\006script\030\001 \001(\t\"\364\001\n\013ChannelDat"
    "a\022,\n\010badClock\030\n \001(\0132\030.pb.ChannelData.Bad"
    "ClockH\000\022&\n\005badJs\030\013 \001(\0132\025.pb.ChannelData."
    "BadJsH\000\022$\n\004text\030\014 \001(\0132\024.pb.ChannelData.T"
    "extH\000\022&\n\005audio\030\r \001(\0132\025.pb.ChannelData.Au"
    "dioH\000\032\n\n\010BadClock\032\007\n\005BadJs\032\030\n\004Text\022\020\n\010fo"
    "ntSize\030\001 \001(\005\032\007\n\005AudioB\t\n\007channel\"\324\001\n\010Doc"
    "ument\022\031\n\006strips\030\001 \003(\0132\t.pb.Strip\022\027\n\017fram"
    "esPerSecond\030\002 \001(\005\022\022\n\nstartFrame\030\004 \001(\005\022\020\n"
    "\010endFrame\030\005 \001(\005\022,\n\010channels\030\003 \003(\0132\032.pb.D"
    "ocument.ChannelsEntry\032@\n\rChannelsEntry\022\013"
    "\n\003key\030\001 \001(\005\022\036\n\005value\030\002 \001(\0132\017.pb.ChannelD"
    "ata:\0028\001b\006proto3", 615);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "eventsequencer.proto", &protobuf_RegisterTypes);
  Strip::default_instance_ = new Strip();
  Strip_BadJs::default_instance_ = new Strip_BadJs();
  ChannelData::default_instance_ = new ChannelData();
  ChannelData_default_oneof_instance_ = new ChannelDataOneofInstance();
  ChannelData_BadClock::default_instance_ = new ChannelData_BadClock();
  ChannelData_BadJs::default_instance_ = new ChannelData_BadJs();
  ChannelData_Text::default_instance_ = new ChannelData_Text();
  ChannelData_Audio::default_instance_ = new ChannelData_Audio();
  Document::default_instance_ = new Document();
  Strip::default_instance_->InitAsDefaultInstance();
  Strip_BadJs::default_instance_->InitAsDefaultInstance();
  ChannelData::default_instance_->InitAsDefaultInstance();
  ChannelData_BadClock::default_instance_->InitAsDefaultInstance();
  ChannelData_BadJs::default_instance_->InitAsDefaultInstance();
  ChannelData_Text::default_instance_->InitAsDefaultInstance();
  ChannelData_Audio::default_instance_->InitAsDefaultInstance();
  Document::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_eventsequencer_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_eventsequencer_2eproto {
  StaticDescriptorInitializer_eventsequencer_2eproto() {
    protobuf_AddDesc_eventsequencer_2eproto();
  }
} static_descriptor_initializer_eventsequencer_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Strip_BadJs::kScriptFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Strip_BadJs::Strip_BadJs()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.Strip.BadJs)
}

void Strip_BadJs::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Strip_BadJs::Strip_BadJs(const Strip_BadJs& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb.Strip.BadJs)
}

void Strip_BadJs::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  script_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Strip_BadJs::~Strip_BadJs() {
  // @@protoc_insertion_point(destructor:pb.Strip.BadJs)
  SharedDtor();
}

void Strip_BadJs::SharedDtor() {
  script_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Strip_BadJs::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Strip_BadJs::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Strip_BadJs_descriptor_;
}

const Strip_BadJs& Strip_BadJs::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_eventsequencer_2eproto();
  return *default_instance_;
}

Strip_BadJs* Strip_BadJs::default_instance_ = NULL;

Strip_BadJs* Strip_BadJs::New(::google::protobuf::Arena* arena) const {
  Strip_BadJs* n = new Strip_BadJs;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Strip_BadJs::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.Strip.BadJs)
  script_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Strip_BadJs::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.Strip.BadJs)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string script = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_script()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->script().data(), this->script().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb.Strip.BadJs.script"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.Strip.BadJs)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.Strip.BadJs)
  return false;
#undef DO_
}

void Strip_BadJs::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.Strip.BadJs)
  // optional string script = 1;
  if (this->script().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->script().data(), this->script().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.Strip.BadJs.script");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->script(), output);
  }

  // @@protoc_insertion_point(serialize_end:pb.Strip.BadJs)
}

::google::protobuf::uint8* Strip_BadJs::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.Strip.BadJs)
  // optional string script = 1;
  if (this->script().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->script().data(), this->script().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.Strip.BadJs.script");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->script(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb.Strip.BadJs)
  return target;
}

int Strip_BadJs::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pb.Strip.BadJs)
  int total_size = 0;

  // optional string script = 1;
  if (this->script().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->script());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Strip_BadJs::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.Strip.BadJs)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Strip_BadJs* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Strip_BadJs>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.Strip.BadJs)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.Strip.BadJs)
    MergeFrom(*source);
  }
}

void Strip_BadJs::MergeFrom(const Strip_BadJs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.Strip.BadJs)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.script().size() > 0) {

    script_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.script_);
  }
}

void Strip_BadJs::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.Strip.BadJs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Strip_BadJs::CopyFrom(const Strip_BadJs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.Strip.BadJs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Strip_BadJs::IsInitialized() const {

  return true;
}

void Strip_BadJs::Swap(Strip_BadJs* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Strip_BadJs::InternalSwap(Strip_BadJs* other) {
  script_.Swap(&other->script_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Strip_BadJs::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Strip_BadJs_descriptor_;
  metadata.reflection = Strip_BadJs_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Strip::kChannelFieldNumber;
const int Strip::kStartFrameFieldNumber;
const int Strip::kLengthFieldNumber;
const int Strip::kBadJsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Strip::Strip()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.Strip)
}

void Strip::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  badjs_ = const_cast< ::pb::Strip_BadJs*>(&::pb::Strip_BadJs::default_instance());
}

Strip::Strip(const Strip& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb.Strip)
}

void Strip::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  channel_ = 0;
  startframe_ = 0;
  length_ = 0;
  badjs_ = NULL;
}

Strip::~Strip() {
  // @@protoc_insertion_point(destructor:pb.Strip)
  SharedDtor();
}

void Strip::SharedDtor() {
  if (this != default_instance_) {
    delete badjs_;
  }
}

void Strip::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Strip::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Strip_descriptor_;
}

const Strip& Strip::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_eventsequencer_2eproto();
  return *default_instance_;
}

Strip* Strip::default_instance_ = NULL;

Strip* Strip::New(::google::protobuf::Arena* arena) const {
  Strip* n = new Strip;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Strip::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.Strip)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(Strip, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Strip*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(channel_, startframe_);
  length_ = 0;
  if (GetArenaNoVirtual() == NULL && badjs_ != NULL) delete badjs_;
  badjs_ = NULL;

#undef ZR_HELPER_
#undef ZR_

}

bool Strip::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.Strip)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 channel = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &channel_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_startFrame;
        break;
      }

      // optional int32 startFrame = 2;
      case 2: {
        if (tag == 16) {
         parse_startFrame:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &startframe_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_length;
        break;
      }

      // optional int32 length = 3;
      case 3: {
        if (tag == 24) {
         parse_length:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &length_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(82)) goto parse_badJs;
        break;
      }

      // optional .pb.Strip.BadJs badJs = 10;
      case 10: {
        if (tag == 82) {
         parse_badJs:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_badjs()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.Strip)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.Strip)
  return false;
#undef DO_
}

void Strip::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.Strip)
  // optional int32 channel = 1;
  if (this->channel() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->channel(), output);
  }

  // optional int32 startFrame = 2;
  if (this->startframe() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->startframe(), output);
  }

  // optional int32 length = 3;
  if (this->length() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->length(), output);
  }

  // optional .pb.Strip.BadJs badJs = 10;
  if (this->has_badjs()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, *this->badjs_, output);
  }

  // @@protoc_insertion_point(serialize_end:pb.Strip)
}

::google::protobuf::uint8* Strip::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.Strip)
  // optional int32 channel = 1;
  if (this->channel() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->channel(), target);
  }

  // optional int32 startFrame = 2;
  if (this->startframe() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->startframe(), target);
  }

  // optional int32 length = 3;
  if (this->length() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->length(), target);
  }

  // optional .pb.Strip.BadJs badJs = 10;
  if (this->has_badjs()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        10, *this->badjs_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb.Strip)
  return target;
}

int Strip::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pb.Strip)
  int total_size = 0;

  // optional int32 channel = 1;
  if (this->channel() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->channel());
  }

  // optional int32 startFrame = 2;
  if (this->startframe() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->startframe());
  }

  // optional int32 length = 3;
  if (this->length() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->length());
  }

  // optional .pb.Strip.BadJs badJs = 10;
  if (this->has_badjs()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->badjs_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Strip::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.Strip)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Strip* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Strip>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.Strip)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.Strip)
    MergeFrom(*source);
  }
}

void Strip::MergeFrom(const Strip& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.Strip)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.channel() != 0) {
    set_channel(from.channel());
  }
  if (from.startframe() != 0) {
    set_startframe(from.startframe());
  }
  if (from.length() != 0) {
    set_length(from.length());
  }
  if (from.has_badjs()) {
    mutable_badjs()->::pb::Strip_BadJs::MergeFrom(from.badjs());
  }
}

void Strip::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.Strip)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Strip::CopyFrom(const Strip& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.Strip)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Strip::IsInitialized() const {

  return true;
}

void Strip::Swap(Strip* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Strip::InternalSwap(Strip* other) {
  std::swap(channel_, other->channel_);
  std::swap(startframe_, other->startframe_);
  std::swap(length_, other->length_);
  std::swap(badjs_, other->badjs_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Strip::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Strip_descriptor_;
  metadata.reflection = Strip_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Strip_BadJs

// optional string script = 1;
void Strip_BadJs::clear_script() {
  script_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Strip_BadJs::script() const {
  // @@protoc_insertion_point(field_get:pb.Strip.BadJs.script)
  return script_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Strip_BadJs::set_script(const ::std::string& value) {
  
  script_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.Strip.BadJs.script)
}
 void Strip_BadJs::set_script(const char* value) {
  
  script_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.Strip.BadJs.script)
}
 void Strip_BadJs::set_script(const char* value, size_t size) {
  
  script_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.Strip.BadJs.script)
}
 ::std::string* Strip_BadJs::mutable_script() {
  
  // @@protoc_insertion_point(field_mutable:pb.Strip.BadJs.script)
  return script_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Strip_BadJs::release_script() {
  // @@protoc_insertion_point(field_release:pb.Strip.BadJs.script)
  
  return script_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Strip_BadJs::set_allocated_script(::std::string* script) {
  if (script != NULL) {
    
  } else {
    
  }
  script_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), script);
  // @@protoc_insertion_point(field_set_allocated:pb.Strip.BadJs.script)
}

// -------------------------------------------------------------------

// Strip

// optional int32 channel = 1;
void Strip::clear_channel() {
  channel_ = 0;
}
 ::google::protobuf::int32 Strip::channel() const {
  // @@protoc_insertion_point(field_get:pb.Strip.channel)
  return channel_;
}
 void Strip::set_channel(::google::protobuf::int32 value) {
  
  channel_ = value;
  // @@protoc_insertion_point(field_set:pb.Strip.channel)
}

// optional int32 startFrame = 2;
void Strip::clear_startframe() {
  startframe_ = 0;
}
 ::google::protobuf::int32 Strip::startframe() const {
  // @@protoc_insertion_point(field_get:pb.Strip.startFrame)
  return startframe_;
}
 void Strip::set_startframe(::google::protobuf::int32 value) {
  
  startframe_ = value;
  // @@protoc_insertion_point(field_set:pb.Strip.startFrame)
}

// optional int32 length = 3;
void Strip::clear_length() {
  length_ = 0;
}
 ::google::protobuf::int32 Strip::length() const {
  // @@protoc_insertion_point(field_get:pb.Strip.length)
  return length_;
}
 void Strip::set_length(::google::protobuf::int32 value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:pb.Strip.length)
}

// optional .pb.Strip.BadJs badJs = 10;
bool Strip::has_badjs() const {
  return !_is_default_instance_ && badjs_ != NULL;
}
void Strip::clear_badjs() {
  if (GetArenaNoVirtual() == NULL && badjs_ != NULL) delete badjs_;
  badjs_ = NULL;
}
const ::pb::Strip_BadJs& Strip::badjs() const {
  // @@protoc_insertion_point(field_get:pb.Strip.badJs)
  return badjs_ != NULL ? *badjs_ : *default_instance_->badjs_;
}
::pb::Strip_BadJs* Strip::mutable_badjs() {
  
  if (badjs_ == NULL) {
    badjs_ = new ::pb::Strip_BadJs;
  }
  // @@protoc_insertion_point(field_mutable:pb.Strip.badJs)
  return badjs_;
}
::pb::Strip_BadJs* Strip::release_badjs() {
  // @@protoc_insertion_point(field_release:pb.Strip.badJs)
  
  ::pb::Strip_BadJs* temp = badjs_;
  badjs_ = NULL;
  return temp;
}
void Strip::set_allocated_badjs(::pb::Strip_BadJs* badjs) {
  delete badjs_;
  badjs_ = badjs;
  if (badjs) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:pb.Strip.badJs)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ChannelData_BadClock::ChannelData_BadClock()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.ChannelData.BadClock)
}

void ChannelData_BadClock::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ChannelData_BadClock::ChannelData_BadClock(const ChannelData_BadClock& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb.ChannelData.BadClock)
}

void ChannelData_BadClock::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

ChannelData_BadClock::~ChannelData_BadClock() {
  // @@protoc_insertion_point(destructor:pb.ChannelData.BadClock)
  SharedDtor();
}

void ChannelData_BadClock::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ChannelData_BadClock::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ChannelData_BadClock::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ChannelData_BadClock_descriptor_;
}

const ChannelData_BadClock& ChannelData_BadClock::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_eventsequencer_2eproto();
  return *default_instance_;
}

ChannelData_BadClock* ChannelData_BadClock::default_instance_ = NULL;

ChannelData_BadClock* ChannelData_BadClock::New(::google::protobuf::Arena* arena) const {
  ChannelData_BadClock* n = new ChannelData_BadClock;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ChannelData_BadClock::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.ChannelData.BadClock)
}

bool ChannelData_BadClock::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.ChannelData.BadClock)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:pb.ChannelData.BadClock)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.ChannelData.BadClock)
  return false;
#undef DO_
}

void ChannelData_BadClock::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.ChannelData.BadClock)
  // @@protoc_insertion_point(serialize_end:pb.ChannelData.BadClock)
}

::google::protobuf::uint8* ChannelData_BadClock::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.ChannelData.BadClock)
  // @@protoc_insertion_point(serialize_to_array_end:pb.ChannelData.BadClock)
  return target;
}

int ChannelData_BadClock::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pb.ChannelData.BadClock)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ChannelData_BadClock::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.ChannelData.BadClock)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ChannelData_BadClock* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ChannelData_BadClock>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.ChannelData.BadClock)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.ChannelData.BadClock)
    MergeFrom(*source);
  }
}

void ChannelData_BadClock::MergeFrom(const ChannelData_BadClock& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.ChannelData.BadClock)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void ChannelData_BadClock::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.ChannelData.BadClock)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ChannelData_BadClock::CopyFrom(const ChannelData_BadClock& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.ChannelData.BadClock)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChannelData_BadClock::IsInitialized() const {

  return true;
}

void ChannelData_BadClock::Swap(ChannelData_BadClock* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ChannelData_BadClock::InternalSwap(ChannelData_BadClock* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ChannelData_BadClock::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ChannelData_BadClock_descriptor_;
  metadata.reflection = ChannelData_BadClock_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ChannelData_BadJs::ChannelData_BadJs()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.ChannelData.BadJs)
}

void ChannelData_BadJs::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ChannelData_BadJs::ChannelData_BadJs(const ChannelData_BadJs& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb.ChannelData.BadJs)
}

void ChannelData_BadJs::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

ChannelData_BadJs::~ChannelData_BadJs() {
  // @@protoc_insertion_point(destructor:pb.ChannelData.BadJs)
  SharedDtor();
}

void ChannelData_BadJs::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ChannelData_BadJs::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ChannelData_BadJs::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ChannelData_BadJs_descriptor_;
}

const ChannelData_BadJs& ChannelData_BadJs::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_eventsequencer_2eproto();
  return *default_instance_;
}

ChannelData_BadJs* ChannelData_BadJs::default_instance_ = NULL;

ChannelData_BadJs* ChannelData_BadJs::New(::google::protobuf::Arena* arena) const {
  ChannelData_BadJs* n = new ChannelData_BadJs;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ChannelData_BadJs::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.ChannelData.BadJs)
}

bool ChannelData_BadJs::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.ChannelData.BadJs)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:pb.ChannelData.BadJs)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.ChannelData.BadJs)
  return false;
#undef DO_
}

void ChannelData_BadJs::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.ChannelData.BadJs)
  // @@protoc_insertion_point(serialize_end:pb.ChannelData.BadJs)
}

::google::protobuf::uint8* ChannelData_BadJs::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.ChannelData.BadJs)
  // @@protoc_insertion_point(serialize_to_array_end:pb.ChannelData.BadJs)
  return target;
}

int ChannelData_BadJs::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pb.ChannelData.BadJs)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ChannelData_BadJs::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.ChannelData.BadJs)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ChannelData_BadJs* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ChannelData_BadJs>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.ChannelData.BadJs)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.ChannelData.BadJs)
    MergeFrom(*source);
  }
}

void ChannelData_BadJs::MergeFrom(const ChannelData_BadJs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.ChannelData.BadJs)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void ChannelData_BadJs::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.ChannelData.BadJs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ChannelData_BadJs::CopyFrom(const ChannelData_BadJs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.ChannelData.BadJs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChannelData_BadJs::IsInitialized() const {

  return true;
}

void ChannelData_BadJs::Swap(ChannelData_BadJs* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ChannelData_BadJs::InternalSwap(ChannelData_BadJs* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ChannelData_BadJs::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ChannelData_BadJs_descriptor_;
  metadata.reflection = ChannelData_BadJs_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ChannelData_Text::kFontSizeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ChannelData_Text::ChannelData_Text()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.ChannelData.Text)
}

void ChannelData_Text::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ChannelData_Text::ChannelData_Text(const ChannelData_Text& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb.ChannelData.Text)
}

void ChannelData_Text::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  fontsize_ = 0;
}

ChannelData_Text::~ChannelData_Text() {
  // @@protoc_insertion_point(destructor:pb.ChannelData.Text)
  SharedDtor();
}

void ChannelData_Text::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ChannelData_Text::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ChannelData_Text::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ChannelData_Text_descriptor_;
}

const ChannelData_Text& ChannelData_Text::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_eventsequencer_2eproto();
  return *default_instance_;
}

ChannelData_Text* ChannelData_Text::default_instance_ = NULL;

ChannelData_Text* ChannelData_Text::New(::google::protobuf::Arena* arena) const {
  ChannelData_Text* n = new ChannelData_Text;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ChannelData_Text::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.ChannelData.Text)
  fontsize_ = 0;
}

bool ChannelData_Text::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.ChannelData.Text)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 fontSize = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &fontsize_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.ChannelData.Text)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.ChannelData.Text)
  return false;
#undef DO_
}

void ChannelData_Text::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.ChannelData.Text)
  // optional int32 fontSize = 1;
  if (this->fontsize() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->fontsize(), output);
  }

  // @@protoc_insertion_point(serialize_end:pb.ChannelData.Text)
}

::google::protobuf::uint8* ChannelData_Text::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.ChannelData.Text)
  // optional int32 fontSize = 1;
  if (this->fontsize() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->fontsize(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb.ChannelData.Text)
  return target;
}

int ChannelData_Text::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pb.ChannelData.Text)
  int total_size = 0;

  // optional int32 fontSize = 1;
  if (this->fontsize() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->fontsize());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ChannelData_Text::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.ChannelData.Text)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ChannelData_Text* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ChannelData_Text>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.ChannelData.Text)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.ChannelData.Text)
    MergeFrom(*source);
  }
}

void ChannelData_Text::MergeFrom(const ChannelData_Text& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.ChannelData.Text)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.fontsize() != 0) {
    set_fontsize(from.fontsize());
  }
}

void ChannelData_Text::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.ChannelData.Text)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ChannelData_Text::CopyFrom(const ChannelData_Text& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.ChannelData.Text)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChannelData_Text::IsInitialized() const {

  return true;
}

void ChannelData_Text::Swap(ChannelData_Text* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ChannelData_Text::InternalSwap(ChannelData_Text* other) {
  std::swap(fontsize_, other->fontsize_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ChannelData_Text::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ChannelData_Text_descriptor_;
  metadata.reflection = ChannelData_Text_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ChannelData_Audio::ChannelData_Audio()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.ChannelData.Audio)
}

void ChannelData_Audio::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ChannelData_Audio::ChannelData_Audio(const ChannelData_Audio& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb.ChannelData.Audio)
}

void ChannelData_Audio::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

ChannelData_Audio::~ChannelData_Audio() {
  // @@protoc_insertion_point(destructor:pb.ChannelData.Audio)
  SharedDtor();
}

void ChannelData_Audio::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ChannelData_Audio::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ChannelData_Audio::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ChannelData_Audio_descriptor_;
}

const ChannelData_Audio& ChannelData_Audio::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_eventsequencer_2eproto();
  return *default_instance_;
}

ChannelData_Audio* ChannelData_Audio::default_instance_ = NULL;

ChannelData_Audio* ChannelData_Audio::New(::google::protobuf::Arena* arena) const {
  ChannelData_Audio* n = new ChannelData_Audio;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ChannelData_Audio::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.ChannelData.Audio)
}

bool ChannelData_Audio::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.ChannelData.Audio)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:pb.ChannelData.Audio)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.ChannelData.Audio)
  return false;
#undef DO_
}

void ChannelData_Audio::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.ChannelData.Audio)
  // @@protoc_insertion_point(serialize_end:pb.ChannelData.Audio)
}

::google::protobuf::uint8* ChannelData_Audio::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.ChannelData.Audio)
  // @@protoc_insertion_point(serialize_to_array_end:pb.ChannelData.Audio)
  return target;
}

int ChannelData_Audio::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pb.ChannelData.Audio)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ChannelData_Audio::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.ChannelData.Audio)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ChannelData_Audio* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ChannelData_Audio>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.ChannelData.Audio)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.ChannelData.Audio)
    MergeFrom(*source);
  }
}

void ChannelData_Audio::MergeFrom(const ChannelData_Audio& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.ChannelData.Audio)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void ChannelData_Audio::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.ChannelData.Audio)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ChannelData_Audio::CopyFrom(const ChannelData_Audio& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.ChannelData.Audio)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChannelData_Audio::IsInitialized() const {

  return true;
}

void ChannelData_Audio::Swap(ChannelData_Audio* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ChannelData_Audio::InternalSwap(ChannelData_Audio* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ChannelData_Audio::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ChannelData_Audio_descriptor_;
  metadata.reflection = ChannelData_Audio_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ChannelData::kBadClockFieldNumber;
const int ChannelData::kBadJsFieldNumber;
const int ChannelData::kTextFieldNumber;
const int ChannelData::kAudioFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ChannelData::ChannelData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.ChannelData)
}

void ChannelData::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  ChannelData_default_oneof_instance_->badclock_ = const_cast< ::pb::ChannelData_BadClock*>(&::pb::ChannelData_BadClock::default_instance());
  ChannelData_default_oneof_instance_->badjs_ = const_cast< ::pb::ChannelData_BadJs*>(&::pb::ChannelData_BadJs::default_instance());
  ChannelData_default_oneof_instance_->text_ = const_cast< ::pb::ChannelData_Text*>(&::pb::ChannelData_Text::default_instance());
  ChannelData_default_oneof_instance_->audio_ = const_cast< ::pb::ChannelData_Audio*>(&::pb::ChannelData_Audio::default_instance());
}

ChannelData::ChannelData(const ChannelData& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb.ChannelData)
}

void ChannelData::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  clear_has_channel();
}

ChannelData::~ChannelData() {
  // @@protoc_insertion_point(destructor:pb.ChannelData)
  SharedDtor();
}

void ChannelData::SharedDtor() {
  if (has_channel()) {
    clear_channel();
  }
  if (this != default_instance_) {
  }
}

void ChannelData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ChannelData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ChannelData_descriptor_;
}

const ChannelData& ChannelData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_eventsequencer_2eproto();
  return *default_instance_;
}

ChannelData* ChannelData::default_instance_ = NULL;

ChannelData* ChannelData::New(::google::protobuf::Arena* arena) const {
  ChannelData* n = new ChannelData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ChannelData::clear_channel() {
// @@protoc_insertion_point(one_of_clear_start:pb.ChannelData)
  switch(channel_case()) {
    case kBadClock: {
      delete channel_.badclock_;
      break;
    }
    case kBadJs: {
      delete channel_.badjs_;
      break;
    }
    case kText: {
      delete channel_.text_;
      break;
    }
    case kAudio: {
      delete channel_.audio_;
      break;
    }
    case CHANNEL_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = CHANNEL_NOT_SET;
}


void ChannelData::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.ChannelData)
  clear_channel();
}

bool ChannelData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.ChannelData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .pb.ChannelData.BadClock badClock = 10;
      case 10: {
        if (tag == 82) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_badclock()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_badJs;
        break;
      }

      // optional .pb.ChannelData.BadJs badJs = 11;
      case 11: {
        if (tag == 90) {
         parse_badJs:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_badjs()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(98)) goto parse_text;
        break;
      }

      // optional .pb.ChannelData.Text text = 12;
      case 12: {
        if (tag == 98) {
         parse_text:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_text()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(106)) goto parse_audio;
        break;
      }

      // optional .pb.ChannelData.Audio audio = 13;
      case 13: {
        if (tag == 106) {
         parse_audio:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_audio()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.ChannelData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.ChannelData)
  return false;
#undef DO_
}

void ChannelData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.ChannelData)
  // optional .pb.ChannelData.BadClock badClock = 10;
  if (has_badclock()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, *channel_.badclock_, output);
  }

  // optional .pb.ChannelData.BadJs badJs = 11;
  if (has_badjs()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, *channel_.badjs_, output);
  }

  // optional .pb.ChannelData.Text text = 12;
  if (has_text()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, *channel_.text_, output);
  }

  // optional .pb.ChannelData.Audio audio = 13;
  if (has_audio()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      13, *channel_.audio_, output);
  }

  // @@protoc_insertion_point(serialize_end:pb.ChannelData)
}

::google::protobuf::uint8* ChannelData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.ChannelData)
  // optional .pb.ChannelData.BadClock badClock = 10;
  if (has_badclock()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        10, *channel_.badclock_, false, target);
  }

  // optional .pb.ChannelData.BadJs badJs = 11;
  if (has_badjs()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        11, *channel_.badjs_, false, target);
  }

  // optional .pb.ChannelData.Text text = 12;
  if (has_text()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        12, *channel_.text_, false, target);
  }

  // optional .pb.ChannelData.Audio audio = 13;
  if (has_audio()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        13, *channel_.audio_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb.ChannelData)
  return target;
}

int ChannelData::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pb.ChannelData)
  int total_size = 0;

  switch (channel_case()) {
    // optional .pb.ChannelData.BadClock badClock = 10;
    case kBadClock: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *channel_.badclock_);
      break;
    }
    // optional .pb.ChannelData.BadJs badJs = 11;
    case kBadJs: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *channel_.badjs_);
      break;
    }
    // optional .pb.ChannelData.Text text = 12;
    case kText: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *channel_.text_);
      break;
    }
    // optional .pb.ChannelData.Audio audio = 13;
    case kAudio: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *channel_.audio_);
      break;
    }
    case CHANNEL_NOT_SET: {
      break;
    }
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ChannelData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.ChannelData)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ChannelData* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ChannelData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.ChannelData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.ChannelData)
    MergeFrom(*source);
  }
}

void ChannelData::MergeFrom(const ChannelData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.ChannelData)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  switch (from.channel_case()) {
    case kBadClock: {
      mutable_badclock()->::pb::ChannelData_BadClock::MergeFrom(from.badclock());
      break;
    }
    case kBadJs: {
      mutable_badjs()->::pb::ChannelData_BadJs::MergeFrom(from.badjs());
      break;
    }
    case kText: {
      mutable_text()->::pb::ChannelData_Text::MergeFrom(from.text());
      break;
    }
    case kAudio: {
      mutable_audio()->::pb::ChannelData_Audio::MergeFrom(from.audio());
      break;
    }
    case CHANNEL_NOT_SET: {
      break;
    }
  }
}

void ChannelData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.ChannelData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ChannelData::CopyFrom(const ChannelData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.ChannelData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChannelData::IsInitialized() const {

  return true;
}

void ChannelData::Swap(ChannelData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ChannelData::InternalSwap(ChannelData* other) {
  std::swap(channel_, other->channel_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ChannelData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ChannelData_descriptor_;
  metadata.reflection = ChannelData_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ChannelData_BadClock

// -------------------------------------------------------------------

// ChannelData_BadJs

// -------------------------------------------------------------------

// ChannelData_Text

// optional int32 fontSize = 1;
void ChannelData_Text::clear_fontsize() {
  fontsize_ = 0;
}
 ::google::protobuf::int32 ChannelData_Text::fontsize() const {
  // @@protoc_insertion_point(field_get:pb.ChannelData.Text.fontSize)
  return fontsize_;
}
 void ChannelData_Text::set_fontsize(::google::protobuf::int32 value) {
  
  fontsize_ = value;
  // @@protoc_insertion_point(field_set:pb.ChannelData.Text.fontSize)
}

// -------------------------------------------------------------------

// ChannelData_Audio

// -------------------------------------------------------------------

// ChannelData

// optional .pb.ChannelData.BadClock badClock = 10;
bool ChannelData::has_badclock() const {
  return channel_case() == kBadClock;
}
void ChannelData::set_has_badclock() {
  _oneof_case_[0] = kBadClock;
}
void ChannelData::clear_badclock() {
  if (has_badclock()) {
    delete channel_.badclock_;
    clear_has_channel();
  }
}
 const ::pb::ChannelData_BadClock& ChannelData::badclock() const {
  // @@protoc_insertion_point(field_get:pb.ChannelData.badClock)
  return has_badclock()
      ? *channel_.badclock_
      : ::pb::ChannelData_BadClock::default_instance();
}
::pb::ChannelData_BadClock* ChannelData::mutable_badclock() {
  if (!has_badclock()) {
    clear_channel();
    set_has_badclock();
    channel_.badclock_ = new ::pb::ChannelData_BadClock;
  }
  // @@protoc_insertion_point(field_mutable:pb.ChannelData.badClock)
  return channel_.badclock_;
}
::pb::ChannelData_BadClock* ChannelData::release_badclock() {
  // @@protoc_insertion_point(field_release:pb.ChannelData.badClock)
  if (has_badclock()) {
    clear_has_channel();
    ::pb::ChannelData_BadClock* temp = channel_.badclock_;
    channel_.badclock_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void ChannelData::set_allocated_badclock(::pb::ChannelData_BadClock* badclock) {
  clear_channel();
  if (badclock) {
    set_has_badclock();
    channel_.badclock_ = badclock;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.ChannelData.badClock)
}

// optional .pb.ChannelData.BadJs badJs = 11;
bool ChannelData::has_badjs() const {
  return channel_case() == kBadJs;
}
void ChannelData::set_has_badjs() {
  _oneof_case_[0] = kBadJs;
}
void ChannelData::clear_badjs() {
  if (has_badjs()) {
    delete channel_.badjs_;
    clear_has_channel();
  }
}
 const ::pb::ChannelData_BadJs& ChannelData::badjs() const {
  // @@protoc_insertion_point(field_get:pb.ChannelData.badJs)
  return has_badjs()
      ? *channel_.badjs_
      : ::pb::ChannelData_BadJs::default_instance();
}
::pb::ChannelData_BadJs* ChannelData::mutable_badjs() {
  if (!has_badjs()) {
    clear_channel();
    set_has_badjs();
    channel_.badjs_ = new ::pb::ChannelData_BadJs;
  }
  // @@protoc_insertion_point(field_mutable:pb.ChannelData.badJs)
  return channel_.badjs_;
}
::pb::ChannelData_BadJs* ChannelData::release_badjs() {
  // @@protoc_insertion_point(field_release:pb.ChannelData.badJs)
  if (has_badjs()) {
    clear_has_channel();
    ::pb::ChannelData_BadJs* temp = channel_.badjs_;
    channel_.badjs_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void ChannelData::set_allocated_badjs(::pb::ChannelData_BadJs* badjs) {
  clear_channel();
  if (badjs) {
    set_has_badjs();
    channel_.badjs_ = badjs;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.ChannelData.badJs)
}

// optional .pb.ChannelData.Text text = 12;
bool ChannelData::has_text() const {
  return channel_case() == kText;
}
void ChannelData::set_has_text() {
  _oneof_case_[0] = kText;
}
void ChannelData::clear_text() {
  if (has_text()) {
    delete channel_.text_;
    clear_has_channel();
  }
}
 const ::pb::ChannelData_Text& ChannelData::text() const {
  // @@protoc_insertion_point(field_get:pb.ChannelData.text)
  return has_text()
      ? *channel_.text_
      : ::pb::ChannelData_Text::default_instance();
}
::pb::ChannelData_Text* ChannelData::mutable_text() {
  if (!has_text()) {
    clear_channel();
    set_has_text();
    channel_.text_ = new ::pb::ChannelData_Text;
  }
  // @@protoc_insertion_point(field_mutable:pb.ChannelData.text)
  return channel_.text_;
}
::pb::ChannelData_Text* ChannelData::release_text() {
  // @@protoc_insertion_point(field_release:pb.ChannelData.text)
  if (has_text()) {
    clear_has_channel();
    ::pb::ChannelData_Text* temp = channel_.text_;
    channel_.text_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void ChannelData::set_allocated_text(::pb::ChannelData_Text* text) {
  clear_channel();
  if (text) {
    set_has_text();
    channel_.text_ = text;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.ChannelData.text)
}

// optional .pb.ChannelData.Audio audio = 13;
bool ChannelData::has_audio() const {
  return channel_case() == kAudio;
}
void ChannelData::set_has_audio() {
  _oneof_case_[0] = kAudio;
}
void ChannelData::clear_audio() {
  if (has_audio()) {
    delete channel_.audio_;
    clear_has_channel();
  }
}
 const ::pb::ChannelData_Audio& ChannelData::audio() const {
  // @@protoc_insertion_point(field_get:pb.ChannelData.audio)
  return has_audio()
      ? *channel_.audio_
      : ::pb::ChannelData_Audio::default_instance();
}
::pb::ChannelData_Audio* ChannelData::mutable_audio() {
  if (!has_audio()) {
    clear_channel();
    set_has_audio();
    channel_.audio_ = new ::pb::ChannelData_Audio;
  }
  // @@protoc_insertion_point(field_mutable:pb.ChannelData.audio)
  return channel_.audio_;
}
::pb::ChannelData_Audio* ChannelData::release_audio() {
  // @@protoc_insertion_point(field_release:pb.ChannelData.audio)
  if (has_audio()) {
    clear_has_channel();
    ::pb::ChannelData_Audio* temp = channel_.audio_;
    channel_.audio_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void ChannelData::set_allocated_audio(::pb::ChannelData_Audio* audio) {
  clear_channel();
  if (audio) {
    set_has_audio();
    channel_.audio_ = audio;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.ChannelData.audio)
}

bool ChannelData::has_channel() const {
  return channel_case() != CHANNEL_NOT_SET;
}
void ChannelData::clear_has_channel() {
  _oneof_case_[0] = CHANNEL_NOT_SET;
}
ChannelData::ChannelCase ChannelData::channel_case() const {
  return ChannelData::ChannelCase(_oneof_case_[0]);
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Document::kStripsFieldNumber;
const int Document::kFramesPerSecondFieldNumber;
const int Document::kStartFrameFieldNumber;
const int Document::kEndFrameFieldNumber;
const int Document::kChannelsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Document::Document()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.Document)
}

void Document::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Document::Document(const Document& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb.Document)
}

void Document::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  framespersecond_ = 0;
  startframe_ = 0;
  endframe_ = 0;
  channels_.SetAssignDescriptorCallback(
      protobuf_AssignDescriptorsOnce);
  channels_.SetEntryDescriptor(
      &::pb::Document_ChannelsEntry_descriptor_);
}

Document::~Document() {
  // @@protoc_insertion_point(destructor:pb.Document)
  SharedDtor();
}

void Document::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Document::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Document::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Document_descriptor_;
}

const Document& Document::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_eventsequencer_2eproto();
  return *default_instance_;
}

Document* Document::default_instance_ = NULL;

Document* Document::New(::google::protobuf::Arena* arena) const {
  Document* n = new Document;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Document::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.Document)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(Document, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Document*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(framespersecond_, startframe_);
  endframe_ = 0;

#undef ZR_HELPER_
#undef ZR_

  strips_.Clear();
  channels_.Clear();
}

bool Document::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.Document)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .pb.Strip strips = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_strips:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_strips()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_strips;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(16)) goto parse_framesPerSecond;
        break;
      }

      // optional int32 framesPerSecond = 2;
      case 2: {
        if (tag == 16) {
         parse_framesPerSecond:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &framespersecond_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_channels;
        break;
      }

      // map<int32, .pb.ChannelData> channels = 3;
      case 3: {
        if (tag == 26) {
         parse_channels:
          DO_(input->IncrementRecursionDepth());
         parse_loop_channels:
          Document_ChannelsEntry::Parser< ::google::protobuf::internal::MapField<
              ::google::protobuf::int32, ::pb::ChannelData,
              ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
              ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
              0 >,
            ::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData > > parser(&channels_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_loop_channels;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(32)) goto parse_startFrame;
        break;
      }

      // optional int32 startFrame = 4;
      case 4: {
        if (tag == 32) {
         parse_startFrame:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &startframe_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_endFrame;
        break;
      }

      // optional int32 endFrame = 5;
      case 5: {
        if (tag == 40) {
         parse_endFrame:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &endframe_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.Document)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.Document)
  return false;
#undef DO_
}

void Document::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.Document)
  // repeated .pb.Strip strips = 1;
  for (unsigned int i = 0, n = this->strips_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->strips(i), output);
  }

  // optional int32 framesPerSecond = 2;
  if (this->framespersecond() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->framespersecond(), output);
  }

  // map<int32, .pb.ChannelData> channels = 3;
  if (!this->channels().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::int32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (output->IsSerializationDeterminstic() &&
        this->channels().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->channels().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData >::const_iterator
          it = this->channels().begin();
          it != this->channels().end(); ++it, ++n) {
        items[n] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[n], Less());
      ::google::protobuf::scoped_ptr<Document_ChannelsEntry> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(channels_.NewEntryWrapper(
            items[i].second->first, items[i].second->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            3, *entry, output);
      }
    } else {
      ::google::protobuf::scoped_ptr<Document_ChannelsEntry> entry;
      for (::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData >::const_iterator
          it = this->channels().begin();
          it != this->channels().end(); ++it) {
        entry.reset(channels_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            3, *entry, output);
      }
    }
  }

  // optional int32 startFrame = 4;
  if (this->startframe() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->startframe(), output);
  }

  // optional int32 endFrame = 5;
  if (this->endframe() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->endframe(), output);
  }

  // @@protoc_insertion_point(serialize_end:pb.Document)
}

::google::protobuf::uint8* Document::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.Document)
  // repeated .pb.Strip strips = 1;
  for (unsigned int i = 0, n = this->strips_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->strips(i), false, target);
  }

  // optional int32 framesPerSecond = 2;
  if (this->framespersecond() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->framespersecond(), target);
  }

  // map<int32, .pb.ChannelData> channels = 3;
  if (!this->channels().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::int32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (deterministic &&
        this->channels().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->channels().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData >::const_iterator
          it = this->channels().begin();
          it != this->channels().end(); ++it, ++n) {
        items[n] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[n], Less());
      ::google::protobuf::scoped_ptr<Document_ChannelsEntry> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(channels_.NewEntryWrapper(
            items[i].second->first, items[i].second->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       3, *entry, deterministic, target);
;
      }
    } else {
      ::google::protobuf::scoped_ptr<Document_ChannelsEntry> entry;
      for (::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData >::const_iterator
          it = this->channels().begin();
          it != this->channels().end(); ++it) {
        entry.reset(channels_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       3, *entry, deterministic, target);
;
      }
    }
  }

  // optional int32 startFrame = 4;
  if (this->startframe() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->startframe(), target);
  }

  // optional int32 endFrame = 5;
  if (this->endframe() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->endframe(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb.Document)
  return target;
}

int Document::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pb.Document)
  int total_size = 0;

  // optional int32 framesPerSecond = 2;
  if (this->framespersecond() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->framespersecond());
  }

  // optional int32 startFrame = 4;
  if (this->startframe() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->startframe());
  }

  // optional int32 endFrame = 5;
  if (this->endframe() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->endframe());
  }

  // repeated .pb.Strip strips = 1;
  total_size += 1 * this->strips_size();
  for (int i = 0; i < this->strips_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->strips(i));
  }

  // map<int32, .pb.ChannelData> channels = 3;
  total_size += 1 * this->channels_size();
  {
    ::google::protobuf::scoped_ptr<Document_ChannelsEntry> entry;
    for (::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData >::const_iterator
        it = this->channels().begin();
        it != this->channels().end(); ++it) {
      entry.reset(channels_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Document::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.Document)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Document* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Document>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.Document)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.Document)
    MergeFrom(*source);
  }
}

void Document::MergeFrom(const Document& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.Document)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  strips_.MergeFrom(from.strips_);
  channels_.MergeFrom(from.channels_);
  if (from.framespersecond() != 0) {
    set_framespersecond(from.framespersecond());
  }
  if (from.startframe() != 0) {
    set_startframe(from.startframe());
  }
  if (from.endframe() != 0) {
    set_endframe(from.endframe());
  }
}

void Document::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.Document)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Document::CopyFrom(const Document& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.Document)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Document::IsInitialized() const {

  return true;
}

void Document::Swap(Document* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Document::InternalSwap(Document* other) {
  strips_.UnsafeArenaSwap(&other->strips_);
  std::swap(framespersecond_, other->framespersecond_);
  std::swap(startframe_, other->startframe_);
  std::swap(endframe_, other->endframe_);
  channels_.Swap(&other->channels_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Document::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Document_descriptor_;
  metadata.reflection = Document_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Document

// repeated .pb.Strip strips = 1;
int Document::strips_size() const {
  return strips_.size();
}
void Document::clear_strips() {
  strips_.Clear();
}
const ::pb::Strip& Document::strips(int index) const {
  // @@protoc_insertion_point(field_get:pb.Document.strips)
  return strips_.Get(index);
}
::pb::Strip* Document::mutable_strips(int index) {
  // @@protoc_insertion_point(field_mutable:pb.Document.strips)
  return strips_.Mutable(index);
}
::pb::Strip* Document::add_strips() {
  // @@protoc_insertion_point(field_add:pb.Document.strips)
  return strips_.Add();
}
::google::protobuf::RepeatedPtrField< ::pb::Strip >*
Document::mutable_strips() {
  // @@protoc_insertion_point(field_mutable_list:pb.Document.strips)
  return &strips_;
}
const ::google::protobuf::RepeatedPtrField< ::pb::Strip >&
Document::strips() const {
  // @@protoc_insertion_point(field_list:pb.Document.strips)
  return strips_;
}

// optional int32 framesPerSecond = 2;
void Document::clear_framespersecond() {
  framespersecond_ = 0;
}
 ::google::protobuf::int32 Document::framespersecond() const {
  // @@protoc_insertion_point(field_get:pb.Document.framesPerSecond)
  return framespersecond_;
}
 void Document::set_framespersecond(::google::protobuf::int32 value) {
  
  framespersecond_ = value;
  // @@protoc_insertion_point(field_set:pb.Document.framesPerSecond)
}

// optional int32 startFrame = 4;
void Document::clear_startframe() {
  startframe_ = 0;
}
 ::google::protobuf::int32 Document::startframe() const {
  // @@protoc_insertion_point(field_get:pb.Document.startFrame)
  return startframe_;
}
 void Document::set_startframe(::google::protobuf::int32 value) {
  
  startframe_ = value;
  // @@protoc_insertion_point(field_set:pb.Document.startFrame)
}

// optional int32 endFrame = 5;
void Document::clear_endframe() {
  endframe_ = 0;
}
 ::google::protobuf::int32 Document::endframe() const {
  // @@protoc_insertion_point(field_get:pb.Document.endFrame)
  return endframe_;
}
 void Document::set_endframe(::google::protobuf::int32 value) {
  
  endframe_ = value;
  // @@protoc_insertion_point(field_set:pb.Document.endFrame)
}

// map<int32, .pb.ChannelData> channels = 3;
int Document::channels_size() const {
  return channels_.size();
}
void Document::clear_channels() {
  channels_.Clear();
}
 const ::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData >&
Document::channels() const {
  // @@protoc_insertion_point(field_map:pb.Document.channels)
  return channels_.GetMap();
}
 ::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData >*
Document::mutable_channels() {
  // @@protoc_insertion_point(field_mutable_map:pb.Document.channels)
  return channels_.MutableMap();
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)
