// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventsequencer.proto

#ifndef PROTOBUF_eventsequencer_2eproto__INCLUDED
#define PROTOBUF_eventsequencer_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/map.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_eventsequencer_2eproto();
void protobuf_AssignDesc_eventsequencer_2eproto();
void protobuf_ShutdownFile_eventsequencer_2eproto();

class ChannelData;
class ChannelData_Audio;
class ChannelData_BadClock;
class ChannelData_BadJs;
class ChannelData_Text;
class Document;
class Strip;
class Strip_BadJs;

// ===================================================================

class Strip_BadJs : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb.Strip.BadJs) */ {
 public:
  Strip_BadJs();
  virtual ~Strip_BadJs();

  Strip_BadJs(const Strip_BadJs& from);

  inline Strip_BadJs& operator=(const Strip_BadJs& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Strip_BadJs& default_instance();

  void Swap(Strip_BadJs* other);

  // implements Message ----------------------------------------------

  inline Strip_BadJs* New() const { return New(NULL); }

  Strip_BadJs* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Strip_BadJs& from);
  void MergeFrom(const Strip_BadJs& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Strip_BadJs* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string script = 1;
  void clear_script();
  static const int kScriptFieldNumber = 1;
  const ::std::string& script() const;
  void set_script(const ::std::string& value);
  void set_script(const char* value);
  void set_script(const char* value, size_t size);
  ::std::string* mutable_script();
  ::std::string* release_script();
  void set_allocated_script(::std::string* script);

  // @@protoc_insertion_point(class_scope:pb.Strip.BadJs)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr script_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_eventsequencer_2eproto();
  friend void protobuf_AssignDesc_eventsequencer_2eproto();
  friend void protobuf_ShutdownFile_eventsequencer_2eproto();

  void InitAsDefaultInstance();
  static Strip_BadJs* default_instance_;
};
// -------------------------------------------------------------------

class Strip : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb.Strip) */ {
 public:
  Strip();
  virtual ~Strip();

  Strip(const Strip& from);

  inline Strip& operator=(const Strip& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Strip& default_instance();

  void Swap(Strip* other);

  // implements Message ----------------------------------------------

  inline Strip* New() const { return New(NULL); }

  Strip* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Strip& from);
  void MergeFrom(const Strip& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Strip* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Strip_BadJs BadJs;

  // accessors -------------------------------------------------------

  // optional int32 channel = 1;
  void clear_channel();
  static const int kChannelFieldNumber = 1;
  ::google::protobuf::int32 channel() const;
  void set_channel(::google::protobuf::int32 value);

  // optional int32 startFrame = 2;
  void clear_startframe();
  static const int kStartFrameFieldNumber = 2;
  ::google::protobuf::int32 startframe() const;
  void set_startframe(::google::protobuf::int32 value);

  // optional int32 length = 3;
  void clear_length();
  static const int kLengthFieldNumber = 3;
  ::google::protobuf::int32 length() const;
  void set_length(::google::protobuf::int32 value);

  // optional .pb.Strip.BadJs badJs = 10;
  bool has_badjs() const;
  void clear_badjs();
  static const int kBadJsFieldNumber = 10;
  const ::pb::Strip_BadJs& badjs() const;
  ::pb::Strip_BadJs* mutable_badjs();
  ::pb::Strip_BadJs* release_badjs();
  void set_allocated_badjs(::pb::Strip_BadJs* badjs);

  // @@protoc_insertion_point(class_scope:pb.Strip)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 channel_;
  ::google::protobuf::int32 startframe_;
  ::pb::Strip_BadJs* badjs_;
  ::google::protobuf::int32 length_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_eventsequencer_2eproto();
  friend void protobuf_AssignDesc_eventsequencer_2eproto();
  friend void protobuf_ShutdownFile_eventsequencer_2eproto();

  void InitAsDefaultInstance();
  static Strip* default_instance_;
};
// -------------------------------------------------------------------

class ChannelData_BadClock : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb.ChannelData.BadClock) */ {
 public:
  ChannelData_BadClock();
  virtual ~ChannelData_BadClock();

  ChannelData_BadClock(const ChannelData_BadClock& from);

  inline ChannelData_BadClock& operator=(const ChannelData_BadClock& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChannelData_BadClock& default_instance();

  void Swap(ChannelData_BadClock* other);

  // implements Message ----------------------------------------------

  inline ChannelData_BadClock* New() const { return New(NULL); }

  ChannelData_BadClock* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChannelData_BadClock& from);
  void MergeFrom(const ChannelData_BadClock& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ChannelData_BadClock* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:pb.ChannelData.BadClock)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_eventsequencer_2eproto();
  friend void protobuf_AssignDesc_eventsequencer_2eproto();
  friend void protobuf_ShutdownFile_eventsequencer_2eproto();

  void InitAsDefaultInstance();
  static ChannelData_BadClock* default_instance_;
};
// -------------------------------------------------------------------

class ChannelData_BadJs : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb.ChannelData.BadJs) */ {
 public:
  ChannelData_BadJs();
  virtual ~ChannelData_BadJs();

  ChannelData_BadJs(const ChannelData_BadJs& from);

  inline ChannelData_BadJs& operator=(const ChannelData_BadJs& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChannelData_BadJs& default_instance();

  void Swap(ChannelData_BadJs* other);

  // implements Message ----------------------------------------------

  inline ChannelData_BadJs* New() const { return New(NULL); }

  ChannelData_BadJs* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChannelData_BadJs& from);
  void MergeFrom(const ChannelData_BadJs& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ChannelData_BadJs* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:pb.ChannelData.BadJs)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_eventsequencer_2eproto();
  friend void protobuf_AssignDesc_eventsequencer_2eproto();
  friend void protobuf_ShutdownFile_eventsequencer_2eproto();

  void InitAsDefaultInstance();
  static ChannelData_BadJs* default_instance_;
};
// -------------------------------------------------------------------

class ChannelData_Text : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb.ChannelData.Text) */ {
 public:
  ChannelData_Text();
  virtual ~ChannelData_Text();

  ChannelData_Text(const ChannelData_Text& from);

  inline ChannelData_Text& operator=(const ChannelData_Text& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChannelData_Text& default_instance();

  void Swap(ChannelData_Text* other);

  // implements Message ----------------------------------------------

  inline ChannelData_Text* New() const { return New(NULL); }

  ChannelData_Text* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChannelData_Text& from);
  void MergeFrom(const ChannelData_Text& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ChannelData_Text* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 fontSize = 1;
  void clear_fontsize();
  static const int kFontSizeFieldNumber = 1;
  ::google::protobuf::int32 fontsize() const;
  void set_fontsize(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pb.ChannelData.Text)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 fontsize_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_eventsequencer_2eproto();
  friend void protobuf_AssignDesc_eventsequencer_2eproto();
  friend void protobuf_ShutdownFile_eventsequencer_2eproto();

  void InitAsDefaultInstance();
  static ChannelData_Text* default_instance_;
};
// -------------------------------------------------------------------

class ChannelData_Audio : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb.ChannelData.Audio) */ {
 public:
  ChannelData_Audio();
  virtual ~ChannelData_Audio();

  ChannelData_Audio(const ChannelData_Audio& from);

  inline ChannelData_Audio& operator=(const ChannelData_Audio& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChannelData_Audio& default_instance();

  void Swap(ChannelData_Audio* other);

  // implements Message ----------------------------------------------

  inline ChannelData_Audio* New() const { return New(NULL); }

  ChannelData_Audio* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChannelData_Audio& from);
  void MergeFrom(const ChannelData_Audio& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ChannelData_Audio* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:pb.ChannelData.Audio)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_eventsequencer_2eproto();
  friend void protobuf_AssignDesc_eventsequencer_2eproto();
  friend void protobuf_ShutdownFile_eventsequencer_2eproto();

  void InitAsDefaultInstance();
  static ChannelData_Audio* default_instance_;
};
// -------------------------------------------------------------------

class ChannelData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb.ChannelData) */ {
 public:
  ChannelData();
  virtual ~ChannelData();

  ChannelData(const ChannelData& from);

  inline ChannelData& operator=(const ChannelData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChannelData& default_instance();

  enum ChannelCase {
    kBadClock = 10,
    kBadJs = 11,
    kText = 12,
    kAudio = 13,
    CHANNEL_NOT_SET = 0,
  };

  void Swap(ChannelData* other);

  // implements Message ----------------------------------------------

  inline ChannelData* New() const { return New(NULL); }

  ChannelData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChannelData& from);
  void MergeFrom(const ChannelData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ChannelData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ChannelData_BadClock BadClock;
  typedef ChannelData_BadJs BadJs;
  typedef ChannelData_Text Text;
  typedef ChannelData_Audio Audio;

  // accessors -------------------------------------------------------

  // optional .pb.ChannelData.BadClock badClock = 10;
  bool has_badclock() const;
  void clear_badclock();
  static const int kBadClockFieldNumber = 10;
  const ::pb::ChannelData_BadClock& badclock() const;
  ::pb::ChannelData_BadClock* mutable_badclock();
  ::pb::ChannelData_BadClock* release_badclock();
  void set_allocated_badclock(::pb::ChannelData_BadClock* badclock);

  // optional .pb.ChannelData.BadJs badJs = 11;
  bool has_badjs() const;
  void clear_badjs();
  static const int kBadJsFieldNumber = 11;
  const ::pb::ChannelData_BadJs& badjs() const;
  ::pb::ChannelData_BadJs* mutable_badjs();
  ::pb::ChannelData_BadJs* release_badjs();
  void set_allocated_badjs(::pb::ChannelData_BadJs* badjs);

  // optional .pb.ChannelData.Text text = 12;
  bool has_text() const;
  void clear_text();
  static const int kTextFieldNumber = 12;
  const ::pb::ChannelData_Text& text() const;
  ::pb::ChannelData_Text* mutable_text();
  ::pb::ChannelData_Text* release_text();
  void set_allocated_text(::pb::ChannelData_Text* text);

  // optional .pb.ChannelData.Audio audio = 13;
  bool has_audio() const;
  void clear_audio();
  static const int kAudioFieldNumber = 13;
  const ::pb::ChannelData_Audio& audio() const;
  ::pb::ChannelData_Audio* mutable_audio();
  ::pb::ChannelData_Audio* release_audio();
  void set_allocated_audio(::pb::ChannelData_Audio* audio);

  ChannelCase channel_case() const;
  // @@protoc_insertion_point(class_scope:pb.ChannelData)
 private:
  inline void set_has_badclock();
  inline void set_has_badjs();
  inline void set_has_text();
  inline void set_has_audio();

  inline bool has_channel() const;
  void clear_channel();
  inline void clear_has_channel();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  union ChannelUnion {
    ChannelUnion() {}
    ::pb::ChannelData_BadClock* badclock_;
    ::pb::ChannelData_BadJs* badjs_;
    ::pb::ChannelData_Text* text_;
    ::pb::ChannelData_Audio* audio_;
  } channel_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_AddDesc_eventsequencer_2eproto();
  friend void protobuf_AssignDesc_eventsequencer_2eproto();
  friend void protobuf_ShutdownFile_eventsequencer_2eproto();

  void InitAsDefaultInstance();
  static ChannelData* default_instance_;
};
// -------------------------------------------------------------------

class Document : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb.Document) */ {
 public:
  Document();
  virtual ~Document();

  Document(const Document& from);

  inline Document& operator=(const Document& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Document& default_instance();

  void Swap(Document* other);

  // implements Message ----------------------------------------------

  inline Document* New() const { return New(NULL); }

  Document* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Document& from);
  void MergeFrom(const Document& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Document* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // repeated .pb.Strip strips = 1;
  int strips_size() const;
  void clear_strips();
  static const int kStripsFieldNumber = 1;
  const ::pb::Strip& strips(int index) const;
  ::pb::Strip* mutable_strips(int index);
  ::pb::Strip* add_strips();
  ::google::protobuf::RepeatedPtrField< ::pb::Strip >*
      mutable_strips();
  const ::google::protobuf::RepeatedPtrField< ::pb::Strip >&
      strips() const;

  // optional int32 framesPerSecond = 2;
  void clear_framespersecond();
  static const int kFramesPerSecondFieldNumber = 2;
  ::google::protobuf::int32 framespersecond() const;
  void set_framespersecond(::google::protobuf::int32 value);

  // optional int32 startFrame = 4;
  void clear_startframe();
  static const int kStartFrameFieldNumber = 4;
  ::google::protobuf::int32 startframe() const;
  void set_startframe(::google::protobuf::int32 value);

  // optional int32 endFrame = 5;
  void clear_endframe();
  static const int kEndFrameFieldNumber = 5;
  ::google::protobuf::int32 endframe() const;
  void set_endframe(::google::protobuf::int32 value);

  // map<int32, .pb.ChannelData> channels = 3;
  int channels_size() const;
  void clear_channels();
  static const int kChannelsFieldNumber = 3;
  const ::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData >&
      channels() const;
  ::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData >*
      mutable_channels();

  // @@protoc_insertion_point(class_scope:pb.Document)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::pb::Strip > strips_;
  ::google::protobuf::int32 framespersecond_;
  ::google::protobuf::int32 startframe_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::google::protobuf::int32, ::pb::ChannelData,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 >
      Document_ChannelsEntry;
  ::google::protobuf::internal::MapField<
      ::google::protobuf::int32, ::pb::ChannelData,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > channels_;
  ::google::protobuf::int32 endframe_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_eventsequencer_2eproto();
  friend void protobuf_AssignDesc_eventsequencer_2eproto();
  friend void protobuf_ShutdownFile_eventsequencer_2eproto();

  void InitAsDefaultInstance();
  static Document* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Strip_BadJs

// optional string script = 1;
inline void Strip_BadJs::clear_script() {
  script_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Strip_BadJs::script() const {
  // @@protoc_insertion_point(field_get:pb.Strip.BadJs.script)
  return script_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Strip_BadJs::set_script(const ::std::string& value) {
  
  script_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.Strip.BadJs.script)
}
inline void Strip_BadJs::set_script(const char* value) {
  
  script_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.Strip.BadJs.script)
}
inline void Strip_BadJs::set_script(const char* value, size_t size) {
  
  script_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.Strip.BadJs.script)
}
inline ::std::string* Strip_BadJs::mutable_script() {
  
  // @@protoc_insertion_point(field_mutable:pb.Strip.BadJs.script)
  return script_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Strip_BadJs::release_script() {
  // @@protoc_insertion_point(field_release:pb.Strip.BadJs.script)
  
  return script_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Strip_BadJs::set_allocated_script(::std::string* script) {
  if (script != NULL) {
    
  } else {
    
  }
  script_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), script);
  // @@protoc_insertion_point(field_set_allocated:pb.Strip.BadJs.script)
}

// -------------------------------------------------------------------

// Strip

// optional int32 channel = 1;
inline void Strip::clear_channel() {
  channel_ = 0;
}
inline ::google::protobuf::int32 Strip::channel() const {
  // @@protoc_insertion_point(field_get:pb.Strip.channel)
  return channel_;
}
inline void Strip::set_channel(::google::protobuf::int32 value) {
  
  channel_ = value;
  // @@protoc_insertion_point(field_set:pb.Strip.channel)
}

// optional int32 startFrame = 2;
inline void Strip::clear_startframe() {
  startframe_ = 0;
}
inline ::google::protobuf::int32 Strip::startframe() const {
  // @@protoc_insertion_point(field_get:pb.Strip.startFrame)
  return startframe_;
}
inline void Strip::set_startframe(::google::protobuf::int32 value) {
  
  startframe_ = value;
  // @@protoc_insertion_point(field_set:pb.Strip.startFrame)
}

// optional int32 length = 3;
inline void Strip::clear_length() {
  length_ = 0;
}
inline ::google::protobuf::int32 Strip::length() const {
  // @@protoc_insertion_point(field_get:pb.Strip.length)
  return length_;
}
inline void Strip::set_length(::google::protobuf::int32 value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:pb.Strip.length)
}

// optional .pb.Strip.BadJs badJs = 10;
inline bool Strip::has_badjs() const {
  return !_is_default_instance_ && badjs_ != NULL;
}
inline void Strip::clear_badjs() {
  if (GetArenaNoVirtual() == NULL && badjs_ != NULL) delete badjs_;
  badjs_ = NULL;
}
inline const ::pb::Strip_BadJs& Strip::badjs() const {
  // @@protoc_insertion_point(field_get:pb.Strip.badJs)
  return badjs_ != NULL ? *badjs_ : *default_instance_->badjs_;
}
inline ::pb::Strip_BadJs* Strip::mutable_badjs() {
  
  if (badjs_ == NULL) {
    badjs_ = new ::pb::Strip_BadJs;
  }
  // @@protoc_insertion_point(field_mutable:pb.Strip.badJs)
  return badjs_;
}
inline ::pb::Strip_BadJs* Strip::release_badjs() {
  // @@protoc_insertion_point(field_release:pb.Strip.badJs)
  
  ::pb::Strip_BadJs* temp = badjs_;
  badjs_ = NULL;
  return temp;
}
inline void Strip::set_allocated_badjs(::pb::Strip_BadJs* badjs) {
  delete badjs_;
  badjs_ = badjs;
  if (badjs) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:pb.Strip.badJs)
}

// -------------------------------------------------------------------

// ChannelData_BadClock

// -------------------------------------------------------------------

// ChannelData_BadJs

// -------------------------------------------------------------------

// ChannelData_Text

// optional int32 fontSize = 1;
inline void ChannelData_Text::clear_fontsize() {
  fontsize_ = 0;
}
inline ::google::protobuf::int32 ChannelData_Text::fontsize() const {
  // @@protoc_insertion_point(field_get:pb.ChannelData.Text.fontSize)
  return fontsize_;
}
inline void ChannelData_Text::set_fontsize(::google::protobuf::int32 value) {
  
  fontsize_ = value;
  // @@protoc_insertion_point(field_set:pb.ChannelData.Text.fontSize)
}

// -------------------------------------------------------------------

// ChannelData_Audio

// -------------------------------------------------------------------

// ChannelData

// optional .pb.ChannelData.BadClock badClock = 10;
inline bool ChannelData::has_badclock() const {
  return channel_case() == kBadClock;
}
inline void ChannelData::set_has_badclock() {
  _oneof_case_[0] = kBadClock;
}
inline void ChannelData::clear_badclock() {
  if (has_badclock()) {
    delete channel_.badclock_;
    clear_has_channel();
  }
}
inline  const ::pb::ChannelData_BadClock& ChannelData::badclock() const {
  // @@protoc_insertion_point(field_get:pb.ChannelData.badClock)
  return has_badclock()
      ? *channel_.badclock_
      : ::pb::ChannelData_BadClock::default_instance();
}
inline ::pb::ChannelData_BadClock* ChannelData::mutable_badclock() {
  if (!has_badclock()) {
    clear_channel();
    set_has_badclock();
    channel_.badclock_ = new ::pb::ChannelData_BadClock;
  }
  // @@protoc_insertion_point(field_mutable:pb.ChannelData.badClock)
  return channel_.badclock_;
}
inline ::pb::ChannelData_BadClock* ChannelData::release_badclock() {
  // @@protoc_insertion_point(field_release:pb.ChannelData.badClock)
  if (has_badclock()) {
    clear_has_channel();
    ::pb::ChannelData_BadClock* temp = channel_.badclock_;
    channel_.badclock_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void ChannelData::set_allocated_badclock(::pb::ChannelData_BadClock* badclock) {
  clear_channel();
  if (badclock) {
    set_has_badclock();
    channel_.badclock_ = badclock;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.ChannelData.badClock)
}

// optional .pb.ChannelData.BadJs badJs = 11;
inline bool ChannelData::has_badjs() const {
  return channel_case() == kBadJs;
}
inline void ChannelData::set_has_badjs() {
  _oneof_case_[0] = kBadJs;
}
inline void ChannelData::clear_badjs() {
  if (has_badjs()) {
    delete channel_.badjs_;
    clear_has_channel();
  }
}
inline  const ::pb::ChannelData_BadJs& ChannelData::badjs() const {
  // @@protoc_insertion_point(field_get:pb.ChannelData.badJs)
  return has_badjs()
      ? *channel_.badjs_
      : ::pb::ChannelData_BadJs::default_instance();
}
inline ::pb::ChannelData_BadJs* ChannelData::mutable_badjs() {
  if (!has_badjs()) {
    clear_channel();
    set_has_badjs();
    channel_.badjs_ = new ::pb::ChannelData_BadJs;
  }
  // @@protoc_insertion_point(field_mutable:pb.ChannelData.badJs)
  return channel_.badjs_;
}
inline ::pb::ChannelData_BadJs* ChannelData::release_badjs() {
  // @@protoc_insertion_point(field_release:pb.ChannelData.badJs)
  if (has_badjs()) {
    clear_has_channel();
    ::pb::ChannelData_BadJs* temp = channel_.badjs_;
    channel_.badjs_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void ChannelData::set_allocated_badjs(::pb::ChannelData_BadJs* badjs) {
  clear_channel();
  if (badjs) {
    set_has_badjs();
    channel_.badjs_ = badjs;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.ChannelData.badJs)
}

// optional .pb.ChannelData.Text text = 12;
inline bool ChannelData::has_text() const {
  return channel_case() == kText;
}
inline void ChannelData::set_has_text() {
  _oneof_case_[0] = kText;
}
inline void ChannelData::clear_text() {
  if (has_text()) {
    delete channel_.text_;
    clear_has_channel();
  }
}
inline  const ::pb::ChannelData_Text& ChannelData::text() const {
  // @@protoc_insertion_point(field_get:pb.ChannelData.text)
  return has_text()
      ? *channel_.text_
      : ::pb::ChannelData_Text::default_instance();
}
inline ::pb::ChannelData_Text* ChannelData::mutable_text() {
  if (!has_text()) {
    clear_channel();
    set_has_text();
    channel_.text_ = new ::pb::ChannelData_Text;
  }
  // @@protoc_insertion_point(field_mutable:pb.ChannelData.text)
  return channel_.text_;
}
inline ::pb::ChannelData_Text* ChannelData::release_text() {
  // @@protoc_insertion_point(field_release:pb.ChannelData.text)
  if (has_text()) {
    clear_has_channel();
    ::pb::ChannelData_Text* temp = channel_.text_;
    channel_.text_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void ChannelData::set_allocated_text(::pb::ChannelData_Text* text) {
  clear_channel();
  if (text) {
    set_has_text();
    channel_.text_ = text;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.ChannelData.text)
}

// optional .pb.ChannelData.Audio audio = 13;
inline bool ChannelData::has_audio() const {
  return channel_case() == kAudio;
}
inline void ChannelData::set_has_audio() {
  _oneof_case_[0] = kAudio;
}
inline void ChannelData::clear_audio() {
  if (has_audio()) {
    delete channel_.audio_;
    clear_has_channel();
  }
}
inline  const ::pb::ChannelData_Audio& ChannelData::audio() const {
  // @@protoc_insertion_point(field_get:pb.ChannelData.audio)
  return has_audio()
      ? *channel_.audio_
      : ::pb::ChannelData_Audio::default_instance();
}
inline ::pb::ChannelData_Audio* ChannelData::mutable_audio() {
  if (!has_audio()) {
    clear_channel();
    set_has_audio();
    channel_.audio_ = new ::pb::ChannelData_Audio;
  }
  // @@protoc_insertion_point(field_mutable:pb.ChannelData.audio)
  return channel_.audio_;
}
inline ::pb::ChannelData_Audio* ChannelData::release_audio() {
  // @@protoc_insertion_point(field_release:pb.ChannelData.audio)
  if (has_audio()) {
    clear_has_channel();
    ::pb::ChannelData_Audio* temp = channel_.audio_;
    channel_.audio_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void ChannelData::set_allocated_audio(::pb::ChannelData_Audio* audio) {
  clear_channel();
  if (audio) {
    set_has_audio();
    channel_.audio_ = audio;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.ChannelData.audio)
}

inline bool ChannelData::has_channel() const {
  return channel_case() != CHANNEL_NOT_SET;
}
inline void ChannelData::clear_has_channel() {
  _oneof_case_[0] = CHANNEL_NOT_SET;
}
inline ChannelData::ChannelCase ChannelData::channel_case() const {
  return ChannelData::ChannelCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// Document

// repeated .pb.Strip strips = 1;
inline int Document::strips_size() const {
  return strips_.size();
}
inline void Document::clear_strips() {
  strips_.Clear();
}
inline const ::pb::Strip& Document::strips(int index) const {
  // @@protoc_insertion_point(field_get:pb.Document.strips)
  return strips_.Get(index);
}
inline ::pb::Strip* Document::mutable_strips(int index) {
  // @@protoc_insertion_point(field_mutable:pb.Document.strips)
  return strips_.Mutable(index);
}
inline ::pb::Strip* Document::add_strips() {
  // @@protoc_insertion_point(field_add:pb.Document.strips)
  return strips_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::pb::Strip >*
Document::mutable_strips() {
  // @@protoc_insertion_point(field_mutable_list:pb.Document.strips)
  return &strips_;
}
inline const ::google::protobuf::RepeatedPtrField< ::pb::Strip >&
Document::strips() const {
  // @@protoc_insertion_point(field_list:pb.Document.strips)
  return strips_;
}

// optional int32 framesPerSecond = 2;
inline void Document::clear_framespersecond() {
  framespersecond_ = 0;
}
inline ::google::protobuf::int32 Document::framespersecond() const {
  // @@protoc_insertion_point(field_get:pb.Document.framesPerSecond)
  return framespersecond_;
}
inline void Document::set_framespersecond(::google::protobuf::int32 value) {
  
  framespersecond_ = value;
  // @@protoc_insertion_point(field_set:pb.Document.framesPerSecond)
}

// optional int32 startFrame = 4;
inline void Document::clear_startframe() {
  startframe_ = 0;
}
inline ::google::protobuf::int32 Document::startframe() const {
  // @@protoc_insertion_point(field_get:pb.Document.startFrame)
  return startframe_;
}
inline void Document::set_startframe(::google::protobuf::int32 value) {
  
  startframe_ = value;
  // @@protoc_insertion_point(field_set:pb.Document.startFrame)
}

// optional int32 endFrame = 5;
inline void Document::clear_endframe() {
  endframe_ = 0;
}
inline ::google::protobuf::int32 Document::endframe() const {
  // @@protoc_insertion_point(field_get:pb.Document.endFrame)
  return endframe_;
}
inline void Document::set_endframe(::google::protobuf::int32 value) {
  
  endframe_ = value;
  // @@protoc_insertion_point(field_set:pb.Document.endFrame)
}

// map<int32, .pb.ChannelData> channels = 3;
inline int Document::channels_size() const {
  return channels_.size();
}
inline void Document::clear_channels() {
  channels_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData >&
Document::channels() const {
  // @@protoc_insertion_point(field_map:pb.Document.channels)
  return channels_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::pb::ChannelData >*
Document::mutable_channels() {
  // @@protoc_insertion_point(field_mutable_map:pb.Document.channels)
  return channels_.MutableMap();
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_eventsequencer_2eproto__INCLUDED
